language: cpp
matrix:
  include:

    # Build with Linux and gcc.
    - os: linux
      env: CC=gcc-9 CXX=g++-9
      addons: &gcc9
        apt:
          packages:
            - libstdc++-9-dev
            - python3.7.5
            - python3-pip
            - doxygen
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
            
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq g++-9
        - sudo apt-get install -y libboost-test-dev

    # Build with OS X and clang ( Currently disabled due to some compilation problems with Clang
    # The default clang compiler supports C++11.
    #- os: osx
     # env: COMPILER=clang++
     # packages:
      #  - clang-9
       # - libc++-9-dev
        #- libc++abi-9-dev

script:
  #- sudo apt-get install python3.6
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7.5 2
  - pip3 install jinja2 Pygments
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
after_success:
  - git clone git://github.com/mosra/m.css
  - cd m.css/documentation
  - ./doxygen.py /home/travis/build/gopi487krishna/Z/Doxyfile-mcss
  - ls
