language: cpp
matrix:
  include:

    # Build with Linux and gcc.
    - os: linux
      env: CC=gcc-9 CXX=g++-9
      addons: &gcc9
        apt:
          packages:
            - libstdc++-9-dev
          sources:
            - ubuntu-toolchain-r-test
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq g++-9
        - sudo apt-get install -y libboost-test-dev

    # Build with OS X and clang.
    # The default clang compiler supports C++11.
    - os: osx
      env: COMPILER=clang++
      packages:
        - clang-8
        - libc++-8-dev
        - libc++abi-8-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
