version: 2



jobs:
  build:
     machine:
       image: ubuntu-1604:201903-01
     environment:
       PYTHONPATH: "/usr/bin/python3.7"
     steps:
      - checkout
      - run:
          command: 'sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"'
      - run:
          command: 'sudo -E apt-add-repository -y "ppa:deadsnakes/ppa"'  
      - run:
          command: 'sudo apt update'
      - run:
          command: 'sudo apt install software-properties-common'
      - run:
          command: 'sudo apt install python3.7'
      - run:
          command: 'sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1'
      - run:
          command: 'sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2'
      - run:
          command: 'python3 --version'
      - run:
          command: 'sudo -E apt-get -yq --no-install-suggests --no-install-recommends install libstdc++-9-dev'
      - run:
          command: 'sudo apt install python3-pip'
      - run:
          command: 'sudo apt install doxygen'  
      - run:
          command: 'sudo apt-get install -y cmake'
      - run:
          command: 'pip3 install jinja2 Pygments'  
      - run:
          command: 'sudo apt-get update -qq'
      - run:
          command: 'sudo apt-get install -qq g++-9'
      - run:
          command: 'sudo apt-get install -y libboost-test-dev'
       
