version: 2



jobs:
  build:
     machine: true
       image: ubuntu-1604:201903-01
     steps:
      - checkout
      - run:
          command: 'sudo apt-get update'
      - run:
          command: 'sudo apt-get install -y cmake'
      - run:
          command: 'python3 -v'
      - run:
          command: 'pip3 install jinja2 Pygments'  
      - run:
          command: 'sudo apt-get update -qq'
      - run:
          command: 'sudo apt-get install -qq g++-9'
      - run:
          command: 'sudo apt-get install -y libboost-test-dev'
       
