version: 2



jobs:
  build:
     machine:
       image: circleci/classic:201808-01
    environment:
      CC: gcc-9
      CXX: g++-9
    steps:
      - checkout
      - run:
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          command: 'python3 -v
      - run:
          command: 'pip3 install jinja2 Pygments'  
      - run:
          command: 'sudo apt-get update -qq'
      - run:
          command: 'sudo apt-get install -qq g++-9'
      - run:
          command: 'sudo apt-get install -y libboost-test-dev'
       
