version: 2



jobs:
  build:
    docker:
      - image: "debian:stretch"
    environment:
      CC: gcc-9
      CXX: g++-9
    steps:
      - checkout
       - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
       - run:
           command: 'sudo -E apt-add-repository -y ppa:ubuntu-toolchain-r/test'
       - run:
          command: 'sudo -E apt-add-repository -y ppa:deadsnakes/ppa'
       - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
       - run:
          command: 'sudo -E apt-get -yq --no-install-suggests --no-install-recommends install libstdc++-9-dev python3.7 python3-pip doxygen'
       - run:
          command: 'pip3 install jinja2 Pygments'  
       - run:
          command: 'sudo apt-get update -qq'
       - run:
          command: 'sudo apt-get install -qq g++-9'
       - run:
          command: 'sudo apt-get install -y libboost-test-dev'
